//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookRep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eLibraryDbEntities : DbContext
    {
        public eLibraryDbEntities()
            : base("name=eLibraryDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_designation> tbl_designation { get; set; }
        public virtual DbSet<tbl_edition> tbl_edition { get; set; }
        public virtual DbSet<tbl_EligibleStudent> tbl_EligibleStudent { get; set; }
        public virtual DbSet<tbl_faculity_user> tbl_faculity_user { get; set; }
        public virtual DbSet<tbl_Program> tbl_Program { get; set; }
        public virtual DbSet<tbl_School> tbl_School { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
        public virtual DbSet<tbl_SubjectArea> tbl_SubjectArea { get; set; }
        public virtual DbSet<tbl_department> tbl_department { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_Book> tbl_Book { get; set; }
    
        public virtual ObjectResult<sp_bookList_Result> sp_bookList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bookList_Result>("sp_bookList");
        }
    
        public virtual ObjectResult<sp_user_Result> sp_user()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_Result>("sp_user");
        }
    
        public virtual ObjectResult<sp_faculity_Result> sp_faculity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_faculity_Result>("sp_faculity");
        }
    }
}
