//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string email_address { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Activation { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string ConformPassword { get; set; }
    }
}
