//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faculity_user
    {
        public int Id { get; set; }
        public string Email_Address { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DesignationId { get; set; }
        public string Pasword { get; set; }
        public string ConformPassword { get; set; }
        public string SchoolId { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<bool> Activation { get; set; }
    }
}
